train:
  n_epoch: 300
  n_fold: 19
  eval_span: 25
  lr: 0.001

  weight_decay: 1e-3

  batch_size: 128
  batch_size_test: 1


model:
  name: 'attn'
  loss_class_weight: [1.25, 1., 1.25]

  use_spec: False
  n_spec_freq: 96

  n_tce: 2
  d_model: 80
  d_ff: 120
  head: 5

  afr_reduced_cnn_size: 30

  cnn_conv_kernel_size: [50, 400]
  cnn_conv_stride: [6, 50]
  cnn_conv_padding: [24, 200]
  cnn_dropout: 0.5

  position_wise_dropout: 0.1

dataset:
  name: 'sleepedf'
  path: ".\\dataset\\sleepedf"

  n_sub: 19
  n_class: 3

  chs: [0]
  wnd_len: 30
  fs_orig: 100.0
  fs: 100.0

  use_max_min_norm: False
  use_filter: False
  filt_range: [ 0.5, 45 ]

  use_amp_limit: False
  amp_range: [ -850, 600 ]

augment:
  aug_class: [ False, False, False ]
  aug_ratio: [ 0, 0, 2 ]
  noise: True
  noise_snr: [ 20, 30, 40 ]

  scale: True
  scale_range: [ 0.85, 1.16 ]
  scale_step: 0.01
  scale_lim: 0.02

  roll: True
  roll_rate: 0.1
  roll_lim: 5

  shuffle: True
