train:
  n_epoch: 250
  n_fold: 7
  eval_span: 25
  lr: 0.001

  clip_grad_val: 5.0
  weight_decay: 1e-3

  batch_size: 128
  batch_size_test: 1

model:
  name: 'utsn'
  dropout: 0.25
  out_dim: 47
  n_class: 3
  loss_class_weight: [1.25, 1., 1.25]

  use_spec: True
  n_spec_freq: 96
  fft_freq_range: [1.0, 25.0]
  bin_len: 0.25

  conv_layer: 8
  conv_ch: [1, 64, 64, 64, 64, 64, 64, 64, 64]
  conv_stride: [1, 2, 2, 2, 1, 2, 2, 2]
  conv_kernel: [9, 9, 9, 9, 7, 7, 7, 7]

  skip_cnt: 4
  # 96 + 47 * 64
  fc_in: 3104
  fc_drop: 0.10

dataset:
  name: 'sleepedf'
  path: ".\\dataset\\sleepedf"

  n_sub: 7
  n_class: 3

  use_max_min_norm: False

  use_filter: False
  filt_range: [1, 45]

  use_amp_limit: False
  amp_range: [-850, 600]

  chs: [0]
  wnd_len: 30
  fs_orig: 100.0
  fs: 100.0

augment:
  aug_class: [ False, False, False ]
  aug_ratio: [ 1, 1, 2 ]
  noise: True
  noise_snr: [ 20, 30, 40 ]

  scale: True
  scale_range: [0.85, 1.16]
  scale_step: 0.01
  scale_lim: 0.02

  roll: True
  roll_rate: 0.1
  roll_lim: 5

  shuffle: True
